#ifndef __ABSTRACTINTERFACEENUMS__
#define __ABSTRACTINTERFACEENUMS__

#define ABSTRACTINTERFACE_INTERFACE_NAME	0
#define ABSTRACTINTERFACE_IF_TYPE		1
#define ABSTRACTINTERFACE_IFINDEX		2
#define ABSTRACTINTERFACE_ISUP			3
#define ABSTRACTINTERFACE_VRF			4
#define ABSTRACTINTERFACE_END			5

#endif /* __ABSTRACTINTERFACEENUMS__ */
