#ifndef __ETHINTERFACEENUMS__
#define __ETHINTERFACEENUMS__

#include "AbstractInterfaceEnums.h"

#define ETHINTERFACE_VLANID	(ABSTRACTINTERFACE_END + 0)
#define ETHINTERFACE_OP_MODE	(ABSTRACTINTERFACE_END + 1)

#endif /* __ETHINTERFACEENUMS__*/
