#ifndef __PIMCCONFIGENUMS__
#define __PIMCCONFIGENUMS__
#include "AbstractL3ConfigEnums.h"

#define PIMCONFIG_PIM_SPARSE	(ABSTRACTL3CONFIG_END + 0)
#define PIMCONFIG_DR_PRIORITY	(ABSTRACTL3CONFIG_END + 1)
#define PIMCONFIG_TTL_THRESHOLD (ABSTRACTL3CONFIG_END + 2)

#endif /* __PIMCCONFIGENUMS__ */
