#ifndef __ROUTERBGPENUMS__
#define __ROUTERBGPENUMS__

#include "AbstractRouterVRFEnums.h"

#define ROUTERBGP_BGPAREA	(ABSTRACTROUTERVRF_END + 0)
#define ROUTERBGP_BGPDISTANCE	(ABSTRACTROUTERVRF_END + 1)

#endif /* __ROUTERBGPENUMS__ */
