#ifndef __ROUTERPIMENUMS__
#define __ROUTERPIMENUMS__

#include "AbstractRouterVRFEnums.h"
#define ROUTERPIM_RP_ADDR	(ABSTRACTROUTERVRF_END + 0)
#define ROUTERPIM_HELLO_TIMER	(ABSTRACTROUTERVRF_END + 1)
#define ROUTERPIM_SSMMAP	(ABSTRACTROUTERVRF_END + 2)
#define ROUTERPIM_MAX_CACHE	(ABSTRACTROUTERVRF_END + 3)
#define ROUTERPIM_NBR_TIMEOUT	(ABSTRACTROUTERVRF_END + 4)
#define ROUTERPIM_JOIN_PRUNE_INTERVAL (ABSTRACTROUTERVRF_END + 5)
#define ROUTERPIM_INACTIVITY_INTERVAL (ABSTRACTROUTERVRF_END + 6)	
#define ROUTERPIM_PRUNE_WAIT_INTERVAL (ABSTRACTROUTERVRF_END + 7)
#define ROUTERPIM_SPT_THRESHOLD	      (ABSTRACTROUTERVRF_END + 8)

#endif /* __ROUTERPIMENUMS__ */

