#ifndef __ROUTEROSPFENUMS__
#define __ROUTEROSPFENUMS__

#include "AbstractRouterVRFEnums.h"
#define ROUTEROSPF_OSPFAREA	(ABSTRACTROUTERVRF_END + 0)
#define ROUTEROSPF_OSPFDISTANCE	(ABSTRACTROUTERVRF_END + 1)

#endif /* __ROUTEROSPFENUMS__ */
