#ifndef __VEINTERFACEENUMS__
#define __VEINTERFACEENUMS__
#include "AbstractInterfaceEnums.h"

#define VEINTERFACE_VLANID	(ABSTRACTINTERFACE_END + 0)
#define VEINTERFACE_IPADDRESS	(ABSTRACTINTERFACE_END + 1)

#endif /* __VEINTERFACEENUMS__ */
